spring.application.name=warehouse-management-system
spring.datasource.url=jdbc:postgresql://localhost:5432/warehouse_db
spring.datasource.username=postgres
spring.datasource.password=Saai@2005
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8080
